name: deploy-gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Restore tools
      run: dotnet tool restore
    - name: Build example docs
      run: dotnet fake build -t buildExampleDocs
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./gh-pages # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
